FROM ubuntu:latest
LABEL image="frontendstatic"
RUN apt update -y
RUN apt install nginx unzip -y
WORKDIR /var/www/html
COPY oxer.zip .
RUN unzip oxer.zip
RUN mv oxer-html/* .
EXPOSE 80
CMD ["nginx","-g","daemon 0ff;"]
